### post
POST http://localhost:5000/admin/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUxYTUxMjE5ODY4MWUyNTY3NzFmZDI3In0sImlhdCI6MTY5NjIyODg5OSwiZXhwIjoxNjk2ODMzNjk5fQ.55mvLkpse8jfR1pP-0HBX1Gns76g92E-wYuHtsA6s_0

{
  "first_name":"She'rozbek",
  "last_name":"Baxtiyorov",
  "username":"sherozbek17",
  "password":"1234"
}


























### list
GET http://localhost:5000/admin
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUxYTUxMjE5ODY4MWUyNTY3NzFmZDI3In0sImlhdCI6MTY5NjIyODg5OSwiZXhwIjoxNjk2ODMzNjk5fQ.55mvLkpse8jfR1pP-0HBX1Gns76g92E-wYuHtsA6s_0





















### list
GET http://localhost:5000/admin/651a517e98681e256771fd2a
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUxYTUxMjE5ODY4MWUyNTY3NzFmZDI3In0sImlhdCI6MTY5NjIyODg5OSwiZXhwIjoxNjk2ODMzNjk5fQ.55mvLkpse8jfR1pP-0HBX1Gns76g92E-wYuHtsA6s_0




















