### POST
POST http://localhost:5000/category
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUxYTUxMjE5ODY4MWUyNTY3NzFmZDI3In0sImlhdCI6MTY5NjIyODg5OSwiZXhwIjoxNjk2ODMzNjk5fQ.55mvLkpse8jfR1pP-0HBX1Gns76g92E-wYuHtsA6s_0

{
  "name": "Dramma"
}











### LIST
GET http://localhost:5000/category
Content-Type: application/json










### REMOVE
DELETE http://localhost:5000/category/6518f8ae92beda23873a6a9d
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUxYTUxMjE5ODY4MWUyNTY3NzFmZDI3In0sImlhdCI6MTY5NjIyODg5OSwiZXhwIjoxNjk2ODMzNjk5fQ.55mvLkpse8jfR1pP-0HBX1Gns76g92E-wYuHtsA6s_0













### UN REMOVE
DELETE http://localhost:5000/category/un/6518f8ae92beda23873a6a9d
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUxYTUxMjE5ODY4MWUyNTY3NzFmZDI3In0sImlhdCI6MTY5NjIyODg5OSwiZXhwIjoxNjk2ODMzNjk5fQ.55mvLkpse8jfR1pP-0HBX1Gns76g92E-wYuHtsA6s_0















### EDIT
PATCH http://localhost:5000/category/6518f8ae92beda23873a6a9d
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUxYTUxMjE5ODY4MWUyNTY3NzFmZDI3In0sImlhdCI6MTY5NjIyODg5OSwiZXhwIjoxNjk2ODMzNjk5fQ.55mvLkpse8jfR1pP-0HBX1Gns76g92E-wYuHtsA6s_0

{
  "name": "Multi Dramma"
}