### POST
POST http://localhost:5000/type
Content-Type: application/json

{
  "name": "Multifilm"
}











### LIST
GET http://localhost:5000/type
Content-Type: application/json










### REMOVE
DELETE http://localhost:5000/type/65191da3c8a19da7ff2a495b
Content-Type: application/json











### UN REMOVE
DELETE http://localhost:5000/type/un/65191da3c8a19da7ff2a495b
Content-Type: application/json











